<link rel="stylesheet" href="<?=ApplicationPHP::$path.'/app/assets/bootstrap-3.3.7-dist/css/bootstrap.css'?>" type="text/css"/>
<link rel="stylesheet" href="<?=ApplicationPHP::$path.'/app/assets/highcharts/api/css/font-awesome.min.css'?>"/>
<link rel="stylesheet" href="<?=ApplicationPHP::$path.'/app/assets/css/application.css'?>" type="text/css"/>
<script src="<?=ApplicationPHP::$path.'/app/assets/javascript/jquery-3.2.1.js'?>" type="text/javascript"></script>
<script src="<?=ApplicationPHP::$path.'/app/assets/bootstrap-3.3.7-dist/js/bootstrap.js'?>" type="text/javascript"></script>
<script src="<?=ApplicationPHP::$path.'/app/assets/javascript/application.js'?>" type="text/javascript"></script>


<?php
//import templates
require_once ("navbar.phtml");
?>

