<link rel="stylesheet" href="app/assets/bootstrap-3.3.7-dist/css/bootstrap.css" type="text/css"/>
<link rel="stylesheet" href="app/assets/css/application.css" type="text/css"/>
<link rel="stylesheet" href="app/assets/highcharts/api/css/font-awesome.min.css"/>
<script src="app/assets/javascript/jquery-3.2.1.js" type="text/javascript"></script>
<script src="app/assets/bootstrap-3.3.7-dist/js/bootstrap.js" type="text/javascript"></script>
<script src="app/assets/javascript/application.js" type="text/javascript"></script>

<?php
//import templates
require_once ("navbar.phtml");
?>

