<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">ScrumApp</a>
        </div>
        <ul class="nav navbar-nav">
            <li class="active"><a href="/scrumapp/home">Home</a></li>
            <li><a href="/scrumapp/projeto">Projetos</a></li>
            <li><a href="/scrumapp/time">Times</a></li>
            <li><a href="/scrumapp/mensagem">Mensagens</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="#"><span class="glyphicon glyphicon-user"></span> Admin</a></li>
            <li><a href="/scrumapp/login/logoff"><span class="glyphicon glyphicon-log-out"></span> Sair</a></li>
        </ul>
    </div>
</nav>