<meta charset="utf-8">

<?php
require_once ("views/layouts/main.phtml");
?>

<div class="container" id="conteudo">
    <div class="row">
        <div class="col-md-6">
            <div id="graficoAtividadesConcluidasPorProjeto"></div>
        </div>
        <div class="col-md-6">
            <div id="graficoMembrosPorTime"></div>
        </div>
    </div>

</div>

<script src="app/assets/highcharts/code/highcharts.src.js" type="text/javascript"></script>
<script src="app/assets/javascript/home/home.js" type="text/javascript"></script>

