<meta charset="utf-8">

<?php
require_once ("views/layouts/main.phtml");

$projetos = $this->getParams()["projetos"];
?>



<div class="container">

<?php
    if(count($projetos) <= 0) {
?>
        <div class="alert alert-warning"><b>Atenção!</b> Nenhum projeto foi encontrado.
            <a href="/scrumapp/projeto/novo" class="btn btn-primary">
                Novo projeto <i class="fa fa-cubes"></i>
            </a>
        </div>
<?php
    }
    foreach ($projetos as $projeto): ?>
    <div class="col-md-4">
        <div class="projectCard">
            <?php echo $projeto->getNome(); ?>
        </div>
        <div class="col-md-12">
            <span>
                <?php echo $projeto->getDescricao(); ?>
            </span>
        </div>
    </div>
<?php endforeach; ?>
</div>

