<meta charset="utf-8">

<?php
require_once ("views/layouts/main.phtml");

$projetos = View::$params["projetos"];
?>



<div class="container">
    <div class="row">
        <div class="col-md-12 pull-left">
            <h1 style="border-bottom: 1px dotted #ccc;margin-bottom: 20px;">Projetos</h1>
        </div>
    </div>
    <div class="row" style="margin-bottom: 20px;">
        <div class="col-md-5" style="vertical-align: 10px;">
            <a href="/scrumapp/projeto/novo" class="btn btn-primary">
                Novo projeto <i class="fa fa-cubes"></i>
            </a>
        </div>
    </div>
<?php
    if(count($projetos) <= 0) {
?>
        <div class="alert alert-warning"><b>Atenção!</b> Nenhum projeto foi encontrado.
            <a href="/scrumapp/projeto/novo" class="btn btn-primary">
                Novo projeto <i class="fa fa-cubes"></i>
            </a>
        </div>
<?php } ?>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-responsive table-bordered">
                <thead>
                <tr>
                    <th>Nome</th>
                    <th>Descrição</th>
                    <th>Status</th>
                    <th>Data Início</th>
                    <th>Data Término</th>
                    <th>Ações</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($projetos as $projeto): ?>
                    <tr>
                        <td><?=$projeto->getNome();?></td>
                        <td><?=$projeto->getDescricao();?></td>
                        <td>
                           <?php
                                if($projeto->getStatus() == "ANDAMENTO"){
                           ?>
                                    <label class="label label-warning"><?=$projeto->getStatus();?>
                           <?php
                                }else if($projeto->getStatus() == "CANCELADO"){
                           ?>
                                    <label class="label label-danger"><?=$projeto->getStatus();?>
                           <?php
                                }else if($projeto->getStatus() == "CONCLUÍDO"){
                           ?>
                                    <label class="label label-success"><?=$projeto->getStatus();?>
                           <?php
                                }
                           ?>
                        </td>
                        <td><?=date_format(date_create($projeto->getDataInicio()),"d/m/Y");?></td>
                        <td><?=date_format(date_create($projeto->getDataTermino()),"d/m/Y");?></td>
                        <td>
                            <a href="/scrumapp/projeto/edit?id=<?=$projeto->getId();?>" class="btn btn-primary">
                                <i class="fa fa-edit"></i>
                            </a>
                            <a href="/scrumapp/projeto/visualizar?id=<?=$projeto->getId();?>" class="btn btn-primary">
                                <i class="fa fa-eye"></i>
                            </a>
                            <a href="#" id="<?=$projeto->getId();?>" class="btn btn-danger delete">
                                <i class="fa fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

</div>


<script src="<?=ApplicationPHP::$path.'/app/assets/javascript/projeto/projeto.js'?>"></script>