<meta charset="utf-8">
<script src="<?=ApplicationPHP::$path.'/app/assets/javascript/projeto/projeto.js'?>"></script>
<?php
require_once ("views/layouts/main.phtml");
$equipes = View::$params["equipes"];
$projeto = isset(View::$params["projeto"]) ? View::$params["projeto"] : new Projeto();
$projetoEquipe = $projeto->getEquipe() != null ? $projeto->getEquipe()->getId() : null;
?>

<div class="container">
    <div class="row">
        <h1 style="border-bottom: 1px dotted #ccc;margin-bottom: 20px;"><?=($projeto->getId()!=null) ? 'Edita Projeto' : 'Novo Projeto'?></h1>
    </div>
    <div class="row" style="margin-bottom: 20px;">
        <div class="col-md-5" style="padding-left:0px;">
            <a href="/scrumapp/projeto/" class="btn btn-warning">
                Voltar <i class="fa fa-arrow-left"></i>
            </a>
        </div>
    </div>
    <?php if(count(View::$errors) > 0){ ?>
        <div class="alert alert-danger">
            <ul>
                <?php foreach (View::$errors as $error): ?>
                    <li><?=$error?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php
        }else if(count(View::$msgsSucesso) > 0 ){
            echo $this->getDivSuccess();
        }
    ?>
    <div class="row">
        <form method="post" action="/scrumapp/projeto/save" name="formProjeto" id="formProjeto">
            <input type="hidden" name="id" id="id" value="<?=$projeto->getId()?>"
            <div class="row" style="margin-bottom: 10px">
                <div class="form-group" >
                    <div class="col-md-3" style="padding-left: 0px;">
                        <label>Nome</label>
                        <input type="text" name="nome" id="nome" class="form-control" value="<?=$projeto->getNome()?>"/>
                    </div>
                    <div class="col-md-4">
                        <label>Descrição</label>
                        <input type="text" name="descricao" id="descricao" class="form-control" value="<?=$projeto->getDescricao()?>"/>
                    </div>
                    <div class="col-md-4">
                        <label>Equipe</label>
                        <select name="equipe" id="equipe" class="form-control">
                            <?php
                            foreach ($equipes as $equipe):
                                ?>
                                <option <?=($equipe->getId() == $projetoEquipe) ? 'selected' : '';?> value="<?=$equipe->getId();?>"><?=$equipe->getNome()?></option>
                                <?php
                            endforeach;
                            ?>
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <div class="col-md-3" style="padding-left: 0px;">
                        <label>Data de Início</label>
                        <input type="date" name="dataInicial" id="dataInicial" class="form-control" value="<?=$projeto->getDataInicio()?>"/>
                    </div>
                    <div class="col-md-3">
                        <label>Data de Término</label>
                        <input type="date" name="dataTermino" id="dataTermino" class="form-control" value="<?=$projeto->getDataTermino()?>"/>
                    </div>
                    <div class="col-md-3">
                        <label style="vertical-align: 30px">&nbsp;</label>
                        <button class="btn btn-primary saveProjeto" type="submit">
                            Salvar <i class="fa fa-check"></i>
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>

</div>
