<meta charset="utf-8">
<?php
require_once ("views/layouts/main.phtml");
$projeto = View::$params['projeto'];
?>

<div class="container">
    <input type="hidden" name="projetoId" id="projetoId" value="<?=$projeto->getId()?>"/>
    <div class="row">
        <h1 style="border-bottom: 1px dotted #ccc;margin-bottom: 20px;">Sprints
            <a href="#"  class="btn btn-primary novaSprint" style="vertical-align: top">
                Nova Sprint <i class="fa fa-newspaper-o"></i>
            </a>
        </h1>
    </div>
    <div class="row">
        <div class="col-md-4 nopadl">
            <h2 class="sessionSprintTitle">Disponíveis</h2>
            <div class="sessionSprint sprint-disponivel">
                <?php foreach ($projeto->getSprintsDisponiveis() as $sprint): ?>
                    <div class="sprint">
                        <div class="pull-right">
                            <button class="btn btn-sm btn-primary visualizarSprint"
                                    data-nome="<?=$sprint->getNome()?>"
                                    data-id="<?=$sprint->getId()?>"
                                    data-descricao="<?=$sprint->getDescricao()?>">
                                <i class="fa fa-eye"></i>
                            </button>
                        </div>
                        <h3><?=$sprint->getNome()?></h3>
                        <p><?=$sprint->getDescricao()?></p>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="col-md-4 nopadl">
            <h2 class="sessionSprintTitle">Andamento</h2>
            <div class="sessionSprint sprint-andamento">
                <?php foreach ($projeto->getSprintsAndamento() as $sprint): ?>
                    <div class="sprint">
                        <div class="pull-right">
                            <button class="btn btn-sm btn-primary visualizarSprint"
                                    data-nome="<?=$sprint->getNome()?>"
                                    data-id="<?=$sprint->getId()?>"
                                    data-descricao="<?=$sprint->getDescricao()?>">
                                <i class="fa fa-eye"></i>
                            </button>
                        </div>
                        <h3><?=$sprint->getNome()?></h3>
                        <p><?=$sprint->getDescricao()?></p>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="col-md-4 nopadl">
            <h2 class="sessionSprintTitle ">Concluídas</h2>
            <div class="sessionSprint sprint-concluido">
                <?php foreach ($projeto->getSprintsConcluidas() as $sprint): ?>
                    <div class="sprint">
                        <div class="pull-right">
                            <button class="btn btn-sm btn-primary visualizarSprint"
                                    data-nome="<?=$sprint->getNome()?>"
                                    data-id="<?=$sprint->getId()?>"
                                    data-descricao="<?=$sprint->getDescricao()?>">
                                <i class="fa fa-eye"></i>
                            </button>
                            <button class="btn btn-sm btn-primary atribuirSprint" data-id="<?=$sprint->getId()?>"
                                <i class="fa fa-eye"></i>
                            </button>
                        </div>
                        <h3><?=$sprint->getNome()?></h3>
                        <p><?=$sprint->getDescricao()?></p>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="novaSprint" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Nova Sprint</h4>
            </div>
            <div class="modal-body">
                <div class="alert alert-danger erros hide"></div>
                <div class="alert alert-danger mensagens hide"></div>
                <div class="row">
                    <input type="hidden" name="sprintId" id="sprintId" value=""/>
                    <div class="col-md-4">
                        <label>Nome</label>
                        <input type="text" name="nome" id="nome" class="form-control" value=""/>
                    </div>
                    <div class="col-md-4">
                        <label>Descrição</label>
                        <textarea name="descricao" id="descricao" class="form-control"></textarea>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <label>Responsáveis</label>
                        <table class="table table-responsive">
                            <thead>
                            <th>Membro</th>
                            <th>&nbsp;</th>
                            </thead>
                            <tbody>
                            <?php foreach ($projeto->getEquipe()->getMembros() as $membro):?>
                                <tr>
                                    <td><?=$membro->getNome()?></td>
                                    <td><input type="checkbox" name="responsavel[]" value="<?=$membro->getId()?>"></td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar <i class="fa fa-times"></i></button>
                <button type="button" class="btn btn-primary criar">Criar <i class="fa fa-check"></i></button>
            </div>
        </div>
    </div>
</div>

<script src="<?=ApplicationPHP::$path.'/app/assets/javascript/projeto/projeto.js'?>"></script>
