<meta charset="utf-8">

<?php
require_once ("views/layouts/main.phtml");

$times = $this->getParams()["times"];
?>

<div class="container">

    <?php
        if(count($times) <= 0) {
    ?>
            <div class="alert alert-warning"><b>Atenção!</b> Nenhum time foi encontrado.
                <button class="btn btn-primary">
                    Novo Time <i class="fa fa-users"></i>
                </button>
            </div>
    <?php
        }else{
    ?>
            <table class="table table-bordered">

                <thead>
                <tr>
                    <th>Nome</th>
                    <th>Categoria</th>
                    <th>Ações</th>
                </tr>
                </thead>
                <tbody>
                <?php
                foreach ($times as $time):
                    ?>
                    <tr>
                        <td><?=$time->getNome();?></td>
                        <td><?=$time->getCategoria();?></td>
                        <td>
                            <button class="btn btn-sm btn-primary">
                                <i class="fa fa-pencil"></i>
                            </button>
                            <button class="btn btn-sm btn-primary">
                                <i class="fa fa-cubes"></i>
                            </button>
                            <button class="btn btn-sm btn-danger">
                                <i class="fa fa-trash"></i>
                            </button>

                        </td>
                    </tr>
                    <?php
                endforeach;
                ?>
                </tbody>
            </table>
    <?php
        }
    ?>
</div>
