<meta charset="utf-8">

<?php
require_once ("views/layouts/main.phtml");

$times = View::$params["times"];
?>

<div class="container">
    <div class="row">
        <h1 style="border-bottom: 1px dotted #ccc;margin-bottom: 20px;">Times</h1>
    </div>
    <div class="row" style="margin-bottom: 20px;">
        <div class="col-md-5" style="vertical-align: 10px;padding-left: 0px;">
            <a href="/scrumapp/time/novo" class="btn btn-primary">
                Novo Time <i class="fa fa-users"></i>
            </a>
        </div>
    </div>

    <?php
        if(count($times) <= 0) {
    ?>
    <div class="row">
            <div class="alert alert-warning"><b>Atenção!</b> Nenhum time foi encontrado.
                <button class="btn btn-primary">
                    Novo Time <i class="fa fa-users"></i>
                </button>
            </div>
    </div>
    <?php
        }else{
    ?>
        <div class="row">
            <table class="table table-bordered">

                <thead>
                <tr>
                    <th>Nome</th>
                    <th>Categoria</th>
                    <th>Ações</th>
                </tr>
                </thead>
                <tbody>
                <?php
                foreach ($times as $time):
                    ?>
                    <tr>
                        <td><?=$time->getNome();?></td>
                        <td><?=$time->getCategoria();?></td>
                        <td>
                            <a href="/scrumapp/time/edit?id=<?=$time->getId();?>" class="btn btn-primary">
                                <i class="fa fa-pencil"></i>
                            </a>
                            <button class="btn btn-primary">
                                <i class="fa fa-cubes"></i>
                            </button>
                            <button class="btn btn-danger">
                                <i class="fa fa-trash"></i>
                            </button>

                        </td>
                    </tr>
                    <?php
                endforeach;
                ?>
                </tbody>
            </table>
        </div>
    <?php
        }
    ?>
</div>
